#!/bin/sh

if [ "$#" -eq "0" ]; then
	echo "usage: $0 project_name [project_name2] ..."
	exit 1
fi

readlink_f() {
	readlink -f $1 2> /dev/null

	if [ "$?" != "0" ]; then
		cur=$1
		while [ ! -z "${cur}" ]; do
			link="${cur}"
			cur="$( readlink $0 )"
		done
		cd "${link}"
		echo "${PWD}"
	fi
}

crossrcdir="$(dirname "$(readlink_f "${0}")")"
basedir="$(readlink_f "${crossrcdir}/..")"

cd "${basedir}"

mkdir -p "${basedir}/dist"

for proj in "$@"; do
	relsrcdir="src/${proj}"

	srcdir="${basedir}/${relsrcdir}"
	echo "-> Creating project ${proj} in ${srcdir}"

	mkdir -pv "${relsrcdir}" 

	echo "-> Copying skeleton..."
	cp -vprn "build/skel/"* "${relsrcdir}"
done